version: 2
jobs:
  build:
    docker:
      - { image: 'circleci/node:7.10' }
    steps:
      # Checkout the build from Git.
      - checkout

      # Restore any cached node_modules from the last
      # build, if package.json has the same checksum.
      - { restore_cache: { key: 'dependency-cache-{{ checksum "package.json" }}' } }

      # Install dependencies.
      - { run: 'npm install' }

      # Save the content of node_modules to cache for
      # the next build.
      - { save_cache: { key: 'dependency-cache-{{ checksum "package.json" }}', paths: [node_modules] } }
  test:
    docker:
      - { image: 'circleci/node:7.10' }
    steps:
      # Checkout the build from Git.
      - checkout

      # Run the tests configured in package.json.
      - { run: 'npm test' }
